### ISSUE TITLE
킹게더 다크 CCS 투표창 버그 제보

### ISSUE THREAD

**Issue by FelisKatze** [asteriskyg/tgd.kr-naseongkim-CSS#11]
![제목 없음-2](https://user-images.githubusercontent.com/21277685/140612428-94705814-bfb9-47bf-a062-c35e352f66fe.jpg)
![제목 없음-3](https://user-images.githubusercontent.com/21277685/140612433-4934f0c9-55ae-4995-8f5b-630cfeb57479.jpg)
다크CCS 에서 투표창을 보면 드래그 해야 보입니다
그런데 이렇게 제보하는거 맞죠...?

**Comment by asteriskyg** [comment]
안녕하세요, 버그 제보 감사합니다. 확인 후 반영하도록 하겠습니다. 감사합니다.

**Comment by asteriskyg** [comment]
확인 감사합니다. 787cc4550ce15a08e17733488cce973229d9f8ae 커밋에서 수정되었습니다.
