### ISSUE TITLE
관리자버튼 위치 수정

### ISSUE THREAD

**Issue by MeronaCarta** [asteriskyg/tgd.kr-naseongkim-CSS#9]
#article-list #article-list-menu>.btn.cog {
    position: absolute;
    left: 130px;
}

#article-list #article-list-menu>.btn.del {
    position: absolute;
    left: 205px;
}

**Comment by asteriskyg** [comment]
안녕하세요. 커스텀 CSS 적용 후 위 스타일 적용 시 바로 오른쪽에 있는 게시물 검색 영역과 간섭이 없는지 확인 부탁드립니다.

감사합니다.

**Comment by MeronaCarta** [comment]
실측 후 거리를 수정했으니 안심하고 적용하셔도 됩니다

**Comment by asteriskyg** [comment]
확인해 주셔서 감사합니다. 다음 버전 업데이트 때 적용하겠습니다.
